/**
 * IEP progress export — PDF.
 *
 * Renders a print-friendly HTML report and opens the browser's print
 * dialog, where the teacher saves it as PDF ("Save as PDF" is a print
 * destination in every modern browser). This keeps the export
 * dependency-free — no multi-hundred-KB PDF library in the bundle — and
 * produces a clean, paginated document.
 */
import { StudentProfile } from "@/engine/types";
import {
  progressFileBase,
  QUARTER_DAYS,
  summarizeProgress,
} from "./progressReport";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Build the standalone HTML document for the progress report. */
export function buildProgressHtml(
  student: StudentProfile,
  sessions: Parameters<typeof summarizeProgress>[1],
  windowDays = QUARTER_DAYS,
  now = Date.now(),
): string {
  const { context, rows, totals } = summarizeProgress(
    student,
    sessions,
    windowDays,
    now,
  );

  const dataRows = rows
    .map(
      (r) => `
      <tr>
        <td>${escapeHtml(r.date)}</td>
        <td>${escapeHtml(r.domain)}</td>
        <td class="num">${r.correct}/${r.trials}</td>
        <td class="num">${r.accuracyPct}%</td>
        <td>${escapeHtml(r.adaptationDetail)}</td>
        <td>${r.endedEarly ? "ended early" : ""}${
          r.aiGenerated ? (r.endedEarly ? ", AI" : "AI") : ""
        }</td>
      </tr>`,
    )
    .join("");

  const emptyNote = rows.length
    ? ""
    : `<tr><td colspan="6" class="empty">No sessions in this reporting window.</td></tr>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(progressFileBase(student, now))}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
    color: #1F2937; margin: 0; padding: 40px;
  }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .sub { color: #6B7280; font-size: 13px; margin-bottom: 24px; }
  .meta { display: flex; gap: 32px; flex-wrap: wrap; margin-bottom: 24px; }
  .meta div { font-size: 13px; }
  .meta .label { color: #6B7280; text-transform: uppercase; letter-spacing: .04em; font-size: 10px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #E6E1D8; }
  th { color: #446A60; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
  td.num, th.num { text-align: right; white-space: nowrap; }
  tfoot td { font-weight: 600; border-top: 2px solid #BBD3CC; border-bottom: none; }
  .empty { color: #6B7280; text-align: center; padding: 24px; }
  .footnote { margin-top: 28px; color: #6B7280; font-size: 11px; }
  @media print { body { padding: 0.5in; } }
</style>
</head>
<body>
  <h1>Progress report — ${escapeHtml(context.name)}</h1>
  <div class="sub">Reporting window: ${context.windowDays} days ending ${escapeHtml(
    context.endDate,
  )}</div>
  <div class="meta">
    <div><div class="label">Grade</div>${escapeHtml(context.grade)}</div>
    <div><div class="label">Reading level</div>${escapeHtml(
      context.readingLevel,
    )}</div>
    <div><div class="label">Sessions</div>${totals.sessions}</div>
    <div><div class="label">Overall accuracy</div>${totals.accuracyPct}%</div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Date</th><th>Domain</th><th class="num">Correct</th>
        <th class="num">Accuracy</th><th>Adaptations</th><th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${dataRows}${emptyNote}
    </tbody>
    <tfoot>
      <tr>
        <td>Total</td>
        <td>${totals.sessions} sessions</td>
        <td class="num">${totals.correct}/${totals.trials}</td>
        <td class="num">${totals.accuracyPct}%</td>
        <td>${totals.adaptations} adaptation events</td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <div class="footnote">
    Generated by Adaptive DTL. Accuracy and adaptation events are recorded
    on-device. Not a medical or educational diagnostic instrument.
  </div>
</body>
</html>`;
}

/**
 * Open the progress report in a new window and trigger the print dialog.
 * Returns false if the popup was blocked.
 */
export function printProgressReport(
  student: StudentProfile,
  sessions: Parameters<typeof summarizeProgress>[1],
  windowDays = QUARTER_DAYS,
  now = Date.now(),
): boolean {
  const html = buildProgressHtml(student, sessions, windowDays, now);
  const win = window.open("", "_blank", "noopener,noreferrer,width=900,height=700");
  if (!win) return false;
  win.document.open();
  win.document.write(html);
  win.document.close();
  // Give the new document a tick to lay out before printing.
  win.onload = () => {
    win.focus();
    win.print();
  };
  // Fallback if onload doesn't fire (document already complete).
  setTimeout(() => {
    try {
      win.focus();
      win.print();
    } catch {
      /* ignore */
    }
  }, 400);
  return true;
}
