import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/Button";
import {
  DomainId,
  DOMAIN_LABELS,
  SessionRecord,
  StudentProfile,
} from "@/engine/types";
import { sessionRepo } from "@/db/sessionRepo";
import {
  buildProgressCsv,
  downloadCsv,
  progressCsvFilename,
} from "@/lib/csvExport";
import { printProgressReport } from "@/lib/pdfExport";
import {
  Sparkles,
  ChevronRight,
  Eye,
  Play,
  Download,
  FileText,
} from "lucide-react";

// Lazy chunks: Recharts (~210KB raw) and the SessionReplay modal both
// load only when their UI is reached. See BUNDLE.md.
const DomainTrendChart = lazy(() => import("./DomainTrendChart"));
const SessionReplay = lazy(() =>
  import("./SessionReplay").then((m) => ({ default: m.SessionReplay })),
);

interface Props {
  student: StudentProfile;
  onStartSession: (domain: DomainId) => void;
}

export function StudentDetail({ student, onStartSession }: Props) {
  const [sessions, setSessions] = useState<SessionRecord[]>([]);
  const [replaying, setReplaying] = useState<SessionRecord | null>(null);

  useEffect(() => {
    let cancelled = false;
    sessionRepo.listForStudent(student.id).then((rows) => {
      if (!cancelled) setSessions(rows);
    });
    return () => {
      cancelled = true;
    };
  }, [student.id]);

  const byDomain = useMemo(() => {
    const out: Record<DomainId, SessionRecord[]> = {
      sightWords: [],
      moneyId: [],
      communitySigns: [],
    };
    for (const s of sessions) out[s.domain].push(s);
    for (const k of Object.keys(out) as DomainId[]) {
      out[k] = [...out[k]].sort((a, b) => a.startedAt - b.startedAt).slice(-10);
    }
    return out;
  }, [sessions]);

  return (
    <div className="space-y-6">
      <div className="flex items-start gap-4">
        <div className="text-5xl">{student.avatar}</div>
        <div className="flex-1">
          <h2 className="text-2xl font-semibold text-ink">{student.name}</h2>
          <div className="text-sm text-muted">
            {student.grade} grade · reads at {student.readingLevel} · {student.responseMethod}
            {student.lowStim ? " · low-stim" : ""}
          </div>
          {student.note && (
            <div className="mt-2 text-sm text-ink/80 italic">{student.note}</div>
          )}
        </div>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {student.goals.map((g) => (
          <DomainPanel
            key={g}
            domain={g}
            sessions={byDomain[g]}
            onStart={() => onStartSession(g)}
          />
        ))}
      </div>

      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-lg font-semibold text-ink">Recent sessions</h3>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="secondary"
              disabled={sessions.length === 0}
              title="Open a printable progress report to save as PDF"
              onClick={() => printProgressReport(student, sessions)}
            >
              <FileText size={14} /> Export PDF
            </Button>
            <Button
              size="sm"
              variant="secondary"
              disabled={sessions.length === 0}
              title="Download last quarter's accuracy and adaptation events as CSV"
              onClick={() => {
                const csv = buildProgressCsv(student, sessions);
                downloadCsv(progressCsvFilename(student), csv);
              }}
            >
              <Download size={14} /> Export CSV
            </Button>
          </div>
        </div>
        <ul className="divide-y divide-line bg-white border border-line rounded-tile">
          {sessions.slice(0, 12).map((s) => (
            <li key={s.id} className="px-4 py-3 flex flex-wrap items-center gap-3">
              <span className="text-sm text-muted w-32">{relativeDate(s.startedAt)}</span>
              <span className="text-sm font-medium w-44">{DOMAIN_LABELS[s.domain]}</span>
              <span className="text-sm text-ink">{Math.round(s.accuracy * 100)}%</span>
              <span className="text-xs text-muted">{s.trials.length} trials</span>
              {s.aiGenerated && (
                <span
                  title="Trials generated by AI"
                  className="text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-full bg-sage-50 text-sage-600 border border-sage-100"
                >
                  AI
                </span>
              )}
              {s.gazeTrace && s.gazeTrace.length > 0 && (
                <span
                  title="Gaze trace recorded (simulated)"
                  className="text-[11px] inline-flex items-center gap-1 text-muted"
                >
                  <Eye size={11} />
                  gaze
                </span>
              )}
              {s.adaptations.length > 0 && (
                <span className="text-xs text-sage-600 inline-flex items-center gap-1">
                  <Sparkles size={12} />
                  {s.adaptations.length} adaptations
                </span>
              )}
              {s.endedEarly && (
                <span className="text-xs text-coral">ended early</span>
              )}
              <Button
                size="sm"
                variant="ghost"
                onClick={() => setReplaying(s)}
                className="ml-auto"
              >
                <Play size={14} /> Replay
              </Button>
            </li>
          ))}
          {sessions.length === 0 && (
            <li className="px-4 py-6 text-sm text-muted text-center">
              No sessions yet. Start one above when {student.name} is ready.
            </li>
          )}
        </ul>
      </div>

      {replaying && (
        <Suspense fallback={null}>
          <SessionReplay session={replaying} onClose={() => setReplaying(null)} />
        </Suspense>
      )}
    </div>
  );
}

function DomainPanel({
  domain,
  sessions,
  onStart,
}: {
  domain: DomainId;
  sessions: SessionRecord[];
  onStart: () => void;
}) {
  const data = sessions.map((s, i) => ({
    n: i + 1,
    accuracy: Math.round(s.accuracy * 100),
  }));
  const last = sessions.at(-1);
  return (
    <div className="bg-white border border-line rounded-tile p-4">
      <div className="flex items-center justify-between mb-3">
        <div>
          <div className="text-sm font-medium text-ink">{DOMAIN_LABELS[domain]}</div>
          <div className="text-xs text-muted">
            {last
              ? `Last: ${Math.round(last.accuracy * 100)}% · ${relativeDate(last.startedAt)}`
              : "No sessions yet"}
          </div>
        </div>
        <Button size="sm" onClick={onStart}>
          Start <ChevronRight size={16} />
        </Button>
      </div>
      <div className="h-32">
        {data.length > 1 ? (
          <Suspense fallback={<ChartSkeleton />}>
            <DomainTrendChart data={data} />
          </Suspense>
        ) : (
          <div className="h-full flex items-center justify-center text-xs text-muted">
            Run a couple of sessions to see the trend.
          </div>
        )}
      </div>
    </div>
  );
}

function ChartSkeleton() {
  return (
    <div className="h-full w-full flex items-end gap-1 px-2 py-2 opacity-30">
      {[0.3, 0.5, 0.4, 0.6, 0.7, 0.55, 0.75, 0.8, 0.7, 0.85].map((h, i) => (
        <div
          key={i}
          className="flex-1 bg-sage rounded-sm"
          style={{ height: `${h * 100}%` }}
        />
      ))}
    </div>
  );
}

function relativeDate(ts: number): string {
  const days = Math.round((Date.now() - ts) / (1000 * 60 * 60 * 24));
  if (days === 0) return "today";
  if (days === 1) return "yesterday";
  if (days < 7) return `${days} days ago`;
  if (days < 30) return `${Math.floor(days / 7)} wk ago`;
  return new Date(ts).toLocaleDateString();
}
